furniture:
  rotation: true
  yaw: 3
  # Effect lists : 1, 2
  effect: 1
  sound: minecraft:entity.chicken.egg

bossbars:
  color: WHITE
  texts:
  - §6Left click to open menu
  - §cShift to exit furniture shop
  
zone:
  enable: true
  region: ''
  viewer-location: {}
  furniture-location: {}
  exit-location: {}