furniture:
  rotation: true
  yaw: 3
  particle:
  sound:

bossbars:
  color: WHITE
  texts:
    - "§6Left click to open menu"
    - "§cShift to exit furniture shop"
  
zone:
  enable: true
  region: ''
  viewer-location:
    x:
    y:
    z:
    pitch:
    yaw:
    world:
  furniture-location:
    x:
    y:
    z:
    pitch:
    yaw:
    world:
  exit-location:
    x:
    y:
    z:
    pitch:
    yaw:
    world: